### ISSUE TITLE
Where Do I Install Content Files ?

### ISSUE THREAD

**Issue by alienfxfiend** [cookgreen/yr#15]
OK so I managed to fully build it with no errors this time. However, as I run it, it says Needs Content, Also mouse cursor won't display in this screen, so where do I install the *.mix files from YR (I have YR with all *.mix files, just don't know where they go (folder to put them in).. Please help ! P.S: Also please state what .mix files are required, not just the destination folder...
P.P.S: OK got it to work —had to make "yr" folder in My Documents. It is _grand_ thank you so much ! I always wanted this !! I've been playing this game for eons (nostalgia), & now the awesome debug cheats work & I can play by myself with no AI ! c00 thanks !
One thing though, when I selected my Apocalypse Tank & typed "/levelup 4" it just leveled up one stripe veteran & didn't upgrade after that —is that normal, in OpenRA Red Alert & Red Alert 2, they upgrade properly to 4.
I noticed there's no V3 Launcher, replaced with Howitzer ??

**Comment by cookgreen** [comment]
1. As for the levelup problem, I will check it out

2. V3 Launcher will be supported soon, as for Howitzer, I think it just a mission-only unit

**Comment by alienfxfiend** [comment]
>     2. V3 Launcher will be supported soon, as for Howitzer, I think it just a mission-only unit

OK Thanks !
