### ISSUE TITLE
Codebase is full of horrible hacks and should take over some AS/Engine alterations.

### ISSUE THREAD

**Issue by GraionDilach** [cookgreen/yr#37]
It looks like you never looked around the wider community what had it achieved besides taking forcecore/OpenRA.

For example:
GrantExternalConditionWeapon should be substituted with the InstantExplode projectile
RevealMapPower or what that is should be DetonateWeaponPower+RevealShroudWarhead.
ParticleSupportPower => DetonateWeaponPower + ChangeOwnerWarhead+GrantExternalConditionWarhead+SpreadDamage for other stuff.

etc etc.

**Comment by cookgreen** [comment]
This issue will be reopen when ready to check the codebase

**Comment by GraionDilach** [comment]
If you put in the effort to loudly advertise your bad setup, then please also put in the effort to actually accept that your codebase is subpar. Closing this issue is not an acknowledgement.

**Comment by cookgreen** [comment]
As I said before, "This issue will be reopen when ready to check the codebase" means your suggestion has been taken, only lack of time. Unless you can help with this 
:)

**Comment by GraionDilach** [comment]
I'm not wasting my time with incompetent loudmouths.
