### ISSUE TITLE
Soviet War Miner Logic\ Guardian GI's Garrison in Battle Fortresses\ V3 Launcher No Damage

### ISSUE THREAD

**Issue by alienfxfiend** [cookgreen/yr#39]
**#1** Soviet War Miners don't go looking [venture out] for more Ore fields once their nearest is over **#2** Guardian GI aren't garrison-able in Battle Fortresses, **#3** It's nice you added V3 Launchers I appreciate it but they do not do any damage at the moment. _I play Skirmish only so I need the AI fine-tuned (maybe it was because I reduced the tech level I don't know.)_

**Comment by cookgreen** [comment]
No.1 8613a5db20b64fbbbdee56a03d52694c5de9c8cb
No.2 e0e486f7872f47223a2cc081517950862331e720
No.3 2b316da249a76721977e2e5abeb691ca49c89434

**Comment by cookgreen** [comment]
fixed
