### ISSUE TITLE
Drive-By Shooting Auto-Turrets in Latest OpenRA Engine Feature (For YR ?)

### ISSUE THREAD

**Issue by alienfxfiend** [cookgreen/yr#44]
Implement the turrets-turn-capability for tanks to fire at units within range without pursuing them —this is in the latest OpenRA engine update (new feature) ~> "Tanks and other turreted units automatically target nearby units while moving" ### playtest-20190106. https://www.openra.net/ (article on homepage) Would be nice to incorporate that functionality into YR if that's not too much to ask & the YR engine is updatable.
P.S: It can wait, just wanted to mention...

**Comment by cookgreen** [comment]
OpenRA has released the new version, I will update YR mod as soon as possible :)

**Comment by alienfxfiend** [comment]
> 
> 
> OpenRA has released the new version, I will update YR mod as soon as possible :)

Thank you so much !

**Comment by cookgreen** [comment]
YR Mod has updated to `release-20190314`
