### ISSUE TITLE
Installation Errors, Not Working —Help !

### ISSUE THREAD

**Issue by alienfxfiend** [cookgreen/yr#7]
Couldn't get it to install properly, the Wiki is for RA2 not Red Alert 2: Yuri's Revenge, got this message ~> https://pastebin.com/Y5YXVy00 & these https://dl.dropboxusercontent.com/s/0azar0tkn001xms/exception-2018-10-23T071747Z.log & https://dl.dropboxusercontent.com/s/b7qchwhvldnrnr0/exception-2018-10-23T080556Z.log & an x86 Processor Architecture error (says to edit in Configuration Manager, but I don't know how to) —also most importantly, there was a copy error **all** during _Make ~> All_. So the game errored out with command-line when running launch-game. I believe the game never fully installed to begin with —I have RA2 ORA installed, a few weeks back, so it's very new —these were warnings not errors. I have vanilla copies of RA2 & Red Alert 2: Yuri's Revenge so I have all *.MIX files. Please add installation instructions if there are any special locations or folder to put files to. I would really love to play this game & I'am a big fan !! {Windows 10 Pro 1803}

**Comment by cookgreen** [comment]
Seems that you didn't compile the ra2 correctly, please try to compile and run again

**Comment by alienfxfiend** [comment]
> 
> 
> Seems that you didn't compile the ra2 correctly, please try to compile and run again

OK I will try another compression utility other than WinRAR, I think there were 229 files but only 186 files in the extracted folder, trying 7Zip portable, unless you know of any other powerful ones.

**Comment by cookgreen** [comment]
> This is the error I get when compiling, it doesn't declare it in the end, but some files are deleted (I tried reinstalling from scratch): "
> Move-Item : Cannot find path 'D:\Download\yr-master\ra2\ra2\mods\ra2\OpenRA.Mods.RA2.dll' because it does not exist.
> At D:\Download\yr-master\make.ps1:390 char:3
> 
> * ```
>       Move-Item $ra2_dll -Destination $ra2_mod_dir
>   ```
> * ```
>       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   * CategoryInfo          : ObjectNotFound: (D:\Download\yr-...RA.Mods.RA2.dll:String) [Move-Item], ItemNotFoundExce
>     ption
>   * FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
>     "
>     Also it states "Building solution configuration "Debug|x86"." But I have x64 & later during launch-game it says change x86 in Configuration Manager..
>     Do I need to put any RA2 files prior to setup in yr-master's subfolder ?
>     The problem seems to be in ""C:\Users\user\AppData\Local\Temp.NETFramework,Version=v4.5.AssemblyAttributes.cs"" <~ It lags during this operation.

Obviously, your ra2 dll didn't exist at all, means the ra2 dll was not generated by the compile tool. You should check your compile error.

**Comment by alienfxfiend** [comment]
What do I do ? Can you send me a manual build, since the compile is not working ? I tried uncompressing it with 7Zip —maybe the RA2 engine didn't download properly ? I have the .MIX files, just need to get this to work, fusion introduced me to this or I wouldn't have found it. Seems like a golden find, if only I can get it to work..

**Comment by cookgreen** [comment]
I think you even didn't install Visual Studio 2015

**Comment by alienfxfiend** [comment]
> 
> 
> I think you even didn't install Visual Studio 2015

I have Visual Studio: 2015

**Comment by cookgreen** [comment]
> > I think you even didn't install Visual Studio 2015
> 
> I have Visual Studio: 2015 & I did install it myself.
If so, you can open the RA2 solution yourself, and compile to make sure no errors

**Comment by alienfxfiend** [comment]
I tried Build Solution & then running it, but it didn't do anything, when I clicked Start, it loaded but locked up my laptop on "Constructing Pylons." Had to Ctrl+Alt+Del & sign-out. Please help !

**Comment by alienfxfiend** [comment]
> 
> 
> No, no. Seems that it meet the runtime error and blocked your game, so you need to run the game with windowed mode, not fullscreen

OK how do I do that ?

**Comment by cookgreen** [comment]
> > No, no. Seems that it meet the runtime error and blocked your game, so you need to run the game with windowed mode, not fullscreen
> 
> OK how do I do that ? Also Game.Mod=ra in Visual Studio: Community Edition —strange.

https://github.com/OpenRA/OpenRA/wiki/Settings

**Comment by alienfxfiend** [comment]
Got Windowed Mode to work, & thankfully don't have to worry about it locking up the computer, but I get this error & it closes ~> >	OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.OpenRA.Traits.IRulesetLoaded<OpenRA.GameRules.WeaponInfo>.RulesetLoaded(OpenRA.Ruleset rules, OpenRA.GameRules.WeaponInfo info) Line 36	C#

**Comment by cookgreen** [comment]
> Got Windowed Mode to work, & thankfully don't have to worry about it locking up the computer, but I get this error & it closes —no wait I continued it, let's see ~> >	OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.OpenRA.Traits.IRulesetLoaded<OpenRA.GameRules.WeaponInfo>.RulesetLoaded(OpenRA.Ruleset rules, OpenRA.GameRules.WeaponInfo info) Line 36	C#

Can you give the full error log?

**Comment by alienfxfiend** [comment]
> 
> 
> > Got Windowed Mode to work, & thankfully don't have to worry about it locking up the computer, but I get this error & it closes —no wait I continued it, let's see ~> >	OpenRA.Mods.Common.dll!OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.OpenRA.Traits.IRulesetLoaded<OpenRA.GameRules.WeaponInfo>.RulesetLoaded(OpenRA.Ruleset rules, OpenRA.GameRules.WeaponInfo info) Line 36	C#
> 
> Can you give the full error log?

That was from Call Stack.

**Comment by alienfxfiend** [comment]
I think it's to do with my RA2 being 64bit & YR x86..

**Comment by cookgreen** [comment]
> I think it's to do with my RA2 being 64bit & YR x86..

Why your RA2 is 64 bit?

**Comment by alienfxfiend** [comment]
> 
> 
> > I think it's to do with my RA2 being 64bit & YR x86..
> 
> Why your RA2 is 64 bit?

Yes

**Comment by cookgreen** [comment]
> > > I think it's to do with my RA2 being 64bit & YR x86..
> > 
> > 
> > Why your RA2 is 64 bit?
> 
> Yep, though I'am not certain, I got it from GitHub.

I think you should build a RA2 with x86 not x64, I am not sure that OpenRA can support x64 properly

**Comment by alienfxfiend** [comment]
> 
> 
> > > > I think it's to do with my RA2 being 64bit & YR x86..
> > > 
> > > 
> > > Why your RA2 is 64 bit?
> > 
> > 
> > Yep, though I'am not certain, I got it from GitHub.
> 
> I think you should build a RA2 with x86 not x64, I am not sure that OpenRA can support x64 properly

Yeah, thanks so much. What you're doing is great, & groundbreaking..

**Comment by cookgreen** [comment]
> > > > > I think it's to do with my RA2 being 64bit & YR x86..
> > > > 
> > > > 
> > > > Why your RA2 is 64 bit?
> > > 
> > > 
> > > Yep, though I'am not certain, I got it from GitHub.
> > 
> > 
> > I think you should build a RA2 with x86 not x64, I am not sure that OpenRA can support x64 properly
> 
> Yeah, thanks so much. What you're doing is great, & groundbreaking..

If you meet any other problem, please post an new issue, there are too many comments in this issue.....
