### ISSUE TITLE
Crashes on startup on Tumbleweed as commit 63: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by fusion809** [cookgreen/yr#8]
Hi,

It seems I have another bug report for ye, on Tumbleweed Yuri's now crashes as of commit 63 (5468e4e29fad6f8f046566605efdb3a0f5899679), with the error:

```bash
Exception of type `System.AggregateException`: One or more errors occurred.
Inner
  Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
    at OpenRA.Mods.YR.Traits.ParticleSupportPowerInfo.RulesetLoaded (OpenRA.Ruleset rules, OpenRA.ActorInfo ai) [0x00086] in <f3fb9e465b254600b7a27720f4a7ac18>:0
  at OpenRA.Ruleset..ctor (OpenRA.IReadOnlyDictionary`2[TKey,TValue] actors, OpenRA.IReadOnlyDictionary`2[TKey,TValue] weapons, OpenRA.IReadOnlyDictionary`2[TKey,TValue] voices, OpenRA.IReadOnlyDictionary`2[TKey,TValue] notifications, O
```

The full logs are here: 
[yr-20181025.log.zip](https://github.com/cookgreen/yr/files/2513496/yr-20181025.log.zip)

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
(for some reason my local copy of this repo seemed to be a fork, that is why I originally said 65. I re-cloned this repo, checked the commit hash, number, log and the remotes to confirm I was using this repo at commit 63 and I was. Then I copied the ra2 mod folder and built the AppImage again and ran it and received the exact same error)

**Comment by cookgreen** [comment]
What operation did you do when crashed, like build some unit or click somewhere?

**Comment by fusion809** [comment]
It crashed on start up. I didn't click anything, I just saw the splash screen (with the YR logo) and then it crashed.

**Comment by cookgreen** [comment]
> It crashed on start up, before I started a game. I didn't click anything, I just saw the splash screen (with the YR logo) and then it crashed.

fixed
