### ISSUE TITLE
Crash after mod logo shows

### ISSUE THREAD

**Issue by yaaaaa** [cookgreen/yr#9]
OpenRA engine version release-20180307
Red Alert 2 Yuri's Revenge mod version release-20180307
Date: 2018-11-07 10:23:06Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.AggregateException`: Произошла одна или несколько ошибок.
Inner
  Exception of type `System.InvalidOperationException`: Cannot locate type: WithSwimSuitInfo
     в OpenRA.ObjectCreator.<.cctor>b__19(String s) в c:\games\RTS\yr-master\engine\OpenRA.Game\ObjectCreator.cs:строка 78
   в OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args) в c:\games\RTS\yr-master\engine\OpenRA.Game\ObjectCreator.cs:строка 90
   в OpenRA.ObjectCreator.CreateObject[T](String className) в c:\games\RTS\yr-master\engine\OpenRA.Game\ObjectCreator.cs:строка 82
   в OpenRA.ActorInfo.LoadTraitInfo(ObjectCreator creator, String traitName, MiniYaml my) в c:\games\RTS\yr-master\engine\OpenRA.Game\GameRules\ActorInfo.cs:строка 73
   в OpenRA.ActorInfo..ctor(ObjectCreator creator, String name, MiniYaml node) в c:\games\RTS\yr-master\engine\OpenRA.Game\GameRules\ActorInfo.cs:строка 46
   в OpenRA.Ruleset.<>c__DisplayClassa.<LoadDefaults>b__4(MiniYamlNode k) в c:\games\RTS\yr-master\engine\OpenRA.Game\GameRules\Ruleset.cs:строка 111
   в OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue) в c:\games\RTS\yr-master\engine\OpenRA.Game\Exts.cs:строка 376
   в OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSystem, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Func`2 makeObject) в c:\games\RTS\yr-master\engine\OpenRA.Game\GameRules\Ruleset.cs:строка 96
   в OpenRA.Ruleset.<>c__DisplayClassa.<LoadDefaults>b__3() в c:\games\RTS\yr-master\engine\OpenRA.Game\GameRules\Ruleset.cs:строка 110
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
   в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   в System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   в OpenRA.Ruleset.LoadDefaults(ModData modData) в c:\games\RTS\yr-master\engine\OpenRA.Game\GameRules\Ruleset.cs:строка 140
   в OpenRA.ModData.<.ctor>b__3() в c:\games\RTS\yr-master\engine\OpenRA.Game\ModData.cs:строка 95
   в System.Lazy`1.CreateValue()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Lazy`1.get_Value()
   в OpenRA.ModData.get_DefaultRules() в c:\games\RTS\yr-master\engine\OpenRA.Game\ModData.cs:строка 41
   в OpenRA.Ruleset.LoadDefaultsForTileSet(ModData modData, String tileSet) в c:\games\RTS\yr-master\engine\OpenRA.Game\GameRules\Ruleset.cs:строка 151
   в OpenRA.Map.PostInit() в c:\games\RTS\yr-master\engine\OpenRA.Game\Map\Map.cs:строка 408
   в OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package) в c:\games\RTS\yr-master\engine\OpenRA.Game\Map\Map.cs:строка 392
   в OpenRA.ModData.PrepareMap(String uid) в c:\games\RTS\yr-master\engine\OpenRA.Game\ModData.cs:строка 188
   в OpenRA.Game.StartGame(String mapUID, WorldType type) в c:\games\RTS\yr-master\engine\OpenRA.Game\Game.cs:строка 164
   в OpenRA.Game.LoadShellMap() в c:\games\RTS\yr-master\engine\OpenRA.Game\Game.cs:строка 474
   в OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args) в c:\games\RTS\yr-master\engine\OpenRA.Mods.Common\LoadScreens\BlankLoadScreen.cs:строка 100
   в OpenRA.Game.InitializeMod(String mod, Arguments args) в c:\games\RTS\yr-master\engine\OpenRA.Game\Game.cs:строка 461
   в OpenRA.Game.Initialize(Arguments args) в c:\games\RTS\yr-master\engine\OpenRA.Game\Game.cs:строка 366
   в OpenRA.Game.InitializeAndRun(String[] args) в c:\games\RTS\yr-master\engine\OpenRA.Game\Game.cs:строка 251
   в OpenRA.Program.Main(String[] args) в c:\games\RTS\yr-master\engine\OpenRA.Game\Support\Program.cs:строка 37

**Comment by fusion809** [comment]
I get the same error on openSUSE Tumbleweed (Linux).

**Comment by cookgreen** [comment]
mine is fine

**Comment by cookgreen** [comment]
You can reopen this issue when you meet the same error once again

**Comment by yaaaaa** [comment]
this error meets every time, game is crash and not start

**Comment by yaaaaa** [comment]
Game starts without this issue after delete WithSwimSuit strings in infantry yaml file.
WithSwimSuit.cs is not exist in any dirrectory

**Comment by fusion809** [comment]
Occurs every time for me too.
